# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Counter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Counter
  pod 'ReactorKit'
  pod 'RxCocoa'
  pod 'SnapKit', '~> 5.7.0' 

  target 'CounterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CounterUITests' do
    # Pods for testing
  end
  
  post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "15.0"
    end
  end
end
end
